In [ ]:
!pip install cvss

Collecting cvss
  Downloading cvss-3.6-py2.py3-none-any.whl.metadata (3.8 kB)
Downloading cvss-3.6-py2.py3-none-any.whl (31 kB)
Installing collected packages: cvss
Successfully installed cvss-3.6

In [ ]:
import json
import requests
import zipfile
import io
import re
from datetime import datetime, timezone
from cvss import CVSS2, CVSS3, CVSS4

In [ ]:
allCWE = {}
CWEmetricks = {}

In [ ]:
ECOSYSTEMS = {
    "PyPI": "https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip",
    "npm": "https://osv-vulnerabilities.storage.googleapis.com/npm/all.zip",  # в OSV экосистема называется npm
    "Go": "https://osv-vulnerabilities.storage.googleapis.com/Go/all.zip"
}

def download_and_extract_zip(url):
    """Скачивает ZIP-архив и возвращает список JSON-объектов (записей об уязвимостях)"""
    print(f"Загрузка {url}...")
    response = requests.get(url)
    if response.status_code != 200:
        print(f"Ошибка загрузки {url}: {response.status_code}")
        return []

    vulnerabilities = []
    # Открываем ZIP из загруженных байтов
    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        for filename in z.namelist():
            if filename.endswith('.json'):
                with z.open(filename) as f:
                    try:
                        vuln = json.load(f)
                        vulnerabilities.append(vuln)
                    except json.JSONDecodeError:
                        print(f"Ошибка чтения JSON из файла {filename}")
    return vulnerabilities

In [ ]:
pypi_vulnerabilities = download_and_extract_zip(ECOSYSTEMS['PyPI'])
npm_vulnerabilities = download_and_extract_zip(ECOSYSTEMS['npm'])
go_vulnerabilities = download_and_extract_zip(ECOSYSTEMS['Go'])

Загрузка https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip...
Загрузка https://osv-vulnerabilities.storage.googleapis.com/npm/all.zip...
Загрузка https://osv-vulnerabilities.storage.googleapis.com/Go/all.zip...

In [ ]:
for i in range(100):
  print(pypi_vulnerabilities[i]["database_specific"])

{'cwe_ids': ['CWE-20', 'CWE-22', 'CWE-73'], 'github_reviewed': True, 'github_reviewed_at': '2025-03-21T16:32:50Z', 'nvd_published_at': '2025-03-20T10:15:23Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-94'], 'github_reviewed': True, 'github_reviewed_at': '2025-05-20T18:01:52Z', 'nvd_published_at': '2025-05-20T18:15:46Z', 'severity': 'HIGH'}
{'cwe_ids': [], 'github_reviewed': True, 'github_reviewed_at': '2024-02-28T22:58:40Z', 'nvd_published_at': '2024-02-28T20:15:41Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-434', 'CWE-669'], 'github_reviewed': True, 'github_reviewed_at': '2025-04-18T20:24:07Z', 'nvd_published_at': None, 'severity': 'HIGH'}
{'cwe_ids': ['CWE-444'], 'github_reviewed': True, 'github_reviewed_at': '2021-09-17T18:30:53Z', 'nvd_published_at': '2021-09-16T15:15:00Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-20'], 'github_reviewed': True, 'github_reviewed_at': '2023-07-17T22:02:54Z', 'nvd_published_at': '2019-08-22T17:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-200'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-09T15:57:25Z', 'nvd_published_at': '2020-02-19T03:15:00Z', 'severity': 'LOW'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2023-07-31T18:51:11Z', 'nvd_published_at': '2017-03-07T16:59:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-754'], 'github_reviewed': True, 'github_reviewed_at': '2020-03-16T20:55:37Z', 'nvd_published_at': None, 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-601', 'CWE-640'], 'github_reviewed': True, 'github_reviewed_at': '2026-03-04T20:33:21Z', 'nvd_published_at': '2026-03-06T05:16:37Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-502'], 'github_reviewed': True, 'github_reviewed_at': '2019-06-13T15:48:35Z', 'nvd_published_at': '2019-06-06T19:29:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-674'], 'github_reviewed': True, 'github_reviewed_at': '2022-06-29T21:51:23Z', 'nvd_published_at': '2022-06-28T17:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-287'], 'github_reviewed': True, 'github_reviewed_at': '2023-02-08T18:06:23Z', 'nvd_published_at': '2013-03-22T21:55:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-200'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-14T21:27:10Z', 'nvd_published_at': '2014-01-07T18:55:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-129'], 'github_reviewed': True, 'github_reviewed_at': '2021-04-16T23:11:53Z', 'nvd_published_at': None, 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-787'], 'github_reviewed': True, 'github_reviewed_at': '2024-02-01T21:22:04Z', 'nvd_published_at': '2021-09-20T16:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2024-08-26T20:32:02Z', 'nvd_published_at': '2024-08-26T16:15:09Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-287'], 'github_reviewed': True, 'github_reviewed_at': '2020-06-16T20:50:58Z', 'nvd_published_at': '2018-03-13T18:29:00Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-287'], 'github_reviewed': True, 'github_reviewed_at': '2022-09-16T17:11:31Z', 'nvd_published_at': '2022-09-14T11:15:00Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-20', 'CWE-284'], 'github_reviewed': True, 'github_reviewed_at': '2021-04-09T15:42:18Z', 'nvd_published_at': '2021-04-09T16:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-22'], 'github_reviewed': True, 'github_reviewed_at': '2023-04-21T19:39:52Z', 'nvd_published_at': '2023-04-20T21:15:08Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-125'], 'github_reviewed': True, 'github_reviewed_at': '2022-02-03T18:08:22Z', 'nvd_published_at': '2022-02-03T11:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-552'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-14T20:14:49Z', 'nvd_published_at': None, 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-791'], 'github_reviewed': True, 'github_reviewed_at': '2026-04-08T00:06:47Z', 'nvd_published_at': '2026-04-05T11:16:55Z', 'severity': 'LOW'}
{'cwe_ids': ['CWE-362', 'CWE-367'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-06T14:35:39Z', 'nvd_published_at': '2024-05-06T00:15:10Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-1270', 'CWE-287'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-14T21:10:43Z', 'nvd_published_at': '2014-04-01T06:35:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2021-03-26T19:52:12Z', 'nvd_published_at': '2021-03-26T20:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2020-07-20T17:47:32Z', 'nvd_published_at': None, 'severity': 'HIGH'}
{'cwe_ids': ['CWE-617'], 'github_reviewed': True, 'github_reviewed_at': '2022-09-16T22:16:52Z', 'nvd_published_at': '2022-09-16T21:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-400', 'CWE-674'], 'github_reviewed': True, 'github_reviewed_at': '2022-02-04T18:23:58Z', 'nvd_published_at': '2022-02-04T23:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-345'], 'github_reviewed': True, 'github_reviewed_at': '2024-07-05T20:06:40Z', 'nvd_published_at': '2024-07-05T19:15:10Z', 'severity': 'LOW'}
{'cwe_ids': ['CWE-918'], 'github_reviewed': True, 'github_reviewed_at': '2026-05-14T20:19:56Z', 'nvd_published_at': None, 'severity': 'HIGH'}
{'cwe_ids': ['CWE-611'], 'github_reviewed': True, 'github_reviewed_at': '2025-12-01T23:57:53Z', 'nvd_published_at': '2025-11-28T04:16:01Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-190', 'CWE-409', 'CWE-617', 'CWE-704', 'CWE-755', 'CWE-789'], 'github_reviewed': True, 'github_reviewed_at': '2026-02-26T15:20:51Z', 'nvd_published_at': '2026-02-26T00:16:26Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-777'], 'github_reviewed': True, 'github_reviewed_at': '2026-05-05T16:54:31Z', 'nvd_published_at': '2026-05-05T22:16:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-193'], 'github_reviewed': True, 'github_reviewed_at': '2023-03-27T21:31:45Z', 'nvd_published_at': '2023-03-26T19:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-416'], 'github_reviewed': True, 'github_reviewed_at': '2022-02-04T19:37:12Z', 'nvd_published_at': '2022-02-04T23:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-125'], 'github_reviewed': True, 'github_reviewed_at': '2021-05-18T16:54:35Z', 'nvd_published_at': '2021-05-14T20:15:00Z', 'severity': 'LOW'}
{'cwe_ids': ['CWE-200'], 'github_reviewed': True, 'github_reviewed_at': '2024-04-18T16:57:45Z', 'nvd_published_at': '2024-04-18T08:15:38Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2025-05-06T18:51:10Z', 'nvd_published_at': '2025-05-05T19:15:55Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-122'], 'github_reviewed': True, 'github_reviewed_at': '2025-02-18T19:25:51Z', 'nvd_published_at': '2024-11-12T18:15:28Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-323'], 'github_reviewed': True, 'github_reviewed_at': '2024-07-31T21:04:28Z', 'nvd_published_at': '2024-07-31T20:15:06Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-22'], 'github_reviewed': True, 'github_reviewed_at': '2026-04-01T22:17:36Z', 'nvd_published_at': '2026-04-02T18:16:31Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-22'], 'github_reviewed': True, 'github_reviewed_at': '2026-03-04T21:28:42Z', 'nvd_published_at': '2026-03-06T07:16:02Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-693', 'CWE-94'], 'github_reviewed': True, 'github_reviewed_at': '2023-08-29T21:37:11Z', 'nvd_published_at': '2014-09-30T14:55:00Z', 'severity': 'MODERATE'}
{'cwe_ids': [], 'github_reviewed': True, 'github_reviewed_at': '2024-10-28T21:50:04Z', 'nvd_published_at': '2024-10-28T20:15:05Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-918'], 'github_reviewed': True, 'github_reviewed_at': '2022-03-08T18:11:03Z', 'nvd_published_at': '2022-03-07T07:15:00Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-20'], 'github_reviewed': True, 'github_reviewed_at': '2023-08-29T22:33:16Z', 'nvd_published_at': '2012-11-18T23:55:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-306'], 'github_reviewed': True, 'github_reviewed_at': '2026-04-08T21:50:58Z', 'nvd_published_at': '2026-04-09T18:17:02Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-190'], 'github_reviewed': True, 'github_reviewed_at': '2021-10-07T20:35:35Z', 'nvd_published_at': '2017-08-15T16:29:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-787'], 'github_reviewed': True, 'github_reviewed_at': '2026-04-16T01:30:48Z', 'nvd_published_at': None, 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-78'], 'github_reviewed': True, 'github_reviewed_at': '2025-04-16T20:38:00Z', 'nvd_published_at': '2025-04-16T18:16:03Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2025-07-23T19:33:15Z', 'nvd_published_at': '2025-07-23T16:15:26Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-200'], 'github_reviewed': True, 'github_reviewed_at': '2023-08-09T14:26:52Z', 'nvd_published_at': '2023-08-05T07:15:43Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-287'], 'github_reviewed': True, 'github_reviewed_at': '2023-06-06T16:40:42Z', 'nvd_published_at': '2023-06-06T19:15:11Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-20'], 'github_reviewed': True, 'github_reviewed_at': '2025-11-03T21:47:59Z', 'nvd_published_at': '2025-10-03T16:16:20Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-639'], 'github_reviewed': True, 'github_reviewed_at': '2026-05-14T20:28:34Z', 'nvd_published_at': '2026-05-15T20:16:49Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-862'], 'github_reviewed': True, 'github_reviewed_at': '2026-03-27T15:35:19Z', 'nvd_published_at': '2026-03-27T00:16:22Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-369'], 'github_reviewed': True, 'github_reviewed_at': '2021-05-18T17:03:33Z', 'nvd_published_at': '2021-05-14T20:15:00Z', 'severity': 'LOW'}
{'cwe_ids': [], 'github_reviewed': True, 'github_reviewed_at': '2024-10-10T22:11:29Z', 'nvd_published_at': None, 'severity': 'LOW'}
{'cwe_ids': ['CWE-250'], 'github_reviewed': True, 'github_reviewed_at': '2025-10-30T17:08:56Z', 'nvd_published_at': '2025-10-30T10:15:35Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-552', 'CWE-611'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-14T21:30:33Z', 'nvd_published_at': '2023-01-18T17:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-269'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-14T20:47:27Z', 'nvd_published_at': '2014-06-17T14:55:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-369'], 'github_reviewed': True, 'github_reviewed_at': '2024-01-03T22:02:51Z', 'nvd_published_at': '2024-01-03T09:15:11Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-78'], 'github_reviewed': True, 'github_reviewed_at': '2026-04-08T21:52:10Z', 'nvd_published_at': '2026-04-09T20:16:27Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-20'], 'github_reviewed': True, 'github_reviewed_at': '2021-08-24T15:34:22Z', 'nvd_published_at': '2021-08-12T23:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-311'], 'github_reviewed': True, 'github_reviewed_at': '2024-10-10T22:08:51Z', 'nvd_published_at': '2024-10-10T23:15:03Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-617'], 'github_reviewed': True, 'github_reviewed_at': '2021-08-23T19:16:53Z', 'nvd_published_at': '2021-08-12T21:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-322'], 'github_reviewed': True, 'github_reviewed_at': '2026-02-06T22:33:06Z', 'nvd_published_at': '2026-02-06T20:16:09Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-770'], 'github_reviewed': True, 'github_reviewed_at': '2026-02-13T16:16:11Z', 'nvd_published_at': None, 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-77'], 'github_reviewed': True, 'github_reviewed_at': '2024-04-04T17:01:56Z', 'nvd_published_at': '2024-04-04T15:15:39Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-772'], 'github_reviewed': True, 'github_reviewed_at': '2024-11-18T21:02:17Z', 'nvd_published_at': '2024-11-18T20:15:06Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-918'], 'github_reviewed': True, 'github_reviewed_at': '2019-10-24T20:46:04Z', 'nvd_published_at': '2019-10-21T23:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': [], 'github_reviewed': True, 'github_reviewed_at': '2024-04-30T14:42:19Z', 'nvd_published_at': '2012-05-01T19:55:00Z', 'severity': 'HIGH'}
{'cwe_ids': [], 'github_reviewed': True, 'github_reviewed_at': '2024-05-14T21:27:12Z', 'nvd_published_at': '2013-11-05T20:55:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-369'], 'github_reviewed': True, 'github_reviewed_at': '2021-08-24T18:17:31Z', 'nvd_published_at': '2021-08-12T23:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-20', 'CWE-617'], 'github_reviewed': True, 'github_reviewed_at': '2022-11-21T21:54:26Z', 'nvd_published_at': '2022-11-18T22:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-319'], 'github_reviewed': True, 'github_reviewed_at': '2023-08-29T18:46:57Z', 'nvd_published_at': '2013-08-06T02:52:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-400'], 'github_reviewed': True, 'github_reviewed_at': '2020-08-21T16:19:09Z', 'nvd_published_at': None, 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-377'], 'github_reviewed': True, 'github_reviewed_at': '2023-05-19T13:27:42Z', 'nvd_published_at': '2023-05-18T17:15:08Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2022-12-15T23:29:11Z', 'nvd_published_at': '2022-12-15T21:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-287'], 'github_reviewed': True, 'github_reviewed_at': '2023-10-04T14:13:24Z', 'nvd_published_at': '2023-10-03T05:15:49Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-22'], 'github_reviewed': True, 'github_reviewed_at': '2025-10-31T17:39:46Z', 'nvd_published_at': '2025-10-30T17:15:37Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-601'], 'github_reviewed': True, 'github_reviewed_at': '2022-03-08T17:48:14Z', 'nvd_published_at': None, 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-400'], 'github_reviewed': True, 'github_reviewed_at': '2023-08-15T23:28:45Z', 'nvd_published_at': '2014-08-26T14:55:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-502'], 'github_reviewed': True, 'github_reviewed_at': '2024-01-22T21:23:34Z', 'nvd_published_at': '2024-01-21T17:15:44Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-863'], 'github_reviewed': True, 'github_reviewed_at': '2024-05-07T16:53:40Z', 'nvd_published_at': '2024-05-07T14:15:10Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-20', 'CWE-78'], 'github_reviewed': True, 'github_reviewed_at': '2023-02-10T19:55:53Z', 'nvd_published_at': '2023-02-10T20:15:00Z', 'severity': 'LOW'}
{'cwe_ids': ['CWE-20'], 'github_reviewed': True, 'github_reviewed_at': '2024-04-22T22:23:17Z', 'nvd_published_at': '2020-11-06T08:15:00Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-201', 'CWE-209'], 'github_reviewed': True, 'github_reviewed_at': '2023-03-21T22:31:19Z', 'nvd_published_at': '2023-03-22T20:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-67'], 'github_reviewed': True, 'github_reviewed_at': '2026-02-19T20:32:45Z', 'nvd_published_at': '2026-02-21T06:17:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-863'], 'github_reviewed': True, 'github_reviewed_at': '2022-03-28T14:23:45Z', 'nvd_published_at': '2022-03-10T21:15:00Z', 'severity': 'CRITICAL'}
{'cwe_ids': ['CWE-770'], 'github_reviewed': True, 'github_reviewed_at': '2025-07-21T19:34:23Z', 'nvd_published_at': '2025-07-21T20:15:41Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-200'], 'github_reviewed': True, 'github_reviewed_at': '2024-11-22T20:20:55Z', 'nvd_published_at': '2022-03-24T17:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-611'], 'github_reviewed': True, 'github_reviewed_at': '2021-04-07T19:33:49Z', 'nvd_published_at': '2020-12-30T19:15:00Z', 'severity': 'HIGH'}
{'cwe_ids': ['CWE-601'], 'github_reviewed': True, 'github_reviewed_at': '2022-03-25T19:27:39Z', 'nvd_published_at': '2022-03-24T20:15:00Z', 'severity': 'MODERATE'}
{'cwe_ids': [], 'github_reviewed': True, 'github_reviewed_at': '2024-04-22T22:58:16Z', 'nvd_published_at': '2017-04-24T19:59:00Z', 'severity': 'LOW'}
{'cwe_ids': ['CWE-79'], 'github_reviewed': True, 'github_reviewed_at': '2023-08-16T23:06:35Z', 'nvd_published_at': '2014-06-18T14:55:00Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-424'], 'github_reviewed': True, 'github_reviewed_at': '2026-03-17T20:33:15Z', 'nvd_published_at': '2026-03-16T17:16:32Z', 'severity': 'MODERATE'}
{'cwe_ids': ['CWE-190'], 'github_reviewed': True, 'github_reviewed_at': '2021-05-18T23:20:56Z', 'nvd_published_at': '2021-05-14T20:15:00Z', 'severity': 'LOW'}

In [ ]:
ECOSYSTEM_archive = {"PyPI": pypi_vulnerabilities,"npm": npm_vulnerabilities, "Go" : go_vulnerabilities}

In [ ]:
pypi_vulnerabilities

In [75]:
for x in pypi_vulnerabilities:
  if "upstream" in x:
    if len(x["upstream"]) > 0:
      print(1)

In [ ]:
def extract_cvss_severity(vuln):
    """Извлекает числовое значение из CVSS score"""
    severity_list = vuln.get("severity", [])
    for severity in severity_list:
        score_str = severity.get("score")
        match = re.search(r"(\d+\.?\d*)", score_str)
        if not match:
          continue
        if severity.get("type") == "CVSS_V4":
            c = CVSS4(severity.get("score"))
            return c.scores()[0]
        elif severity.get("type") == "CVSS_V3":
            c = CVSS3(severity.get("score"))
            return c.scores()[0]
        else:
            c = CVSS2(severity.get("score"))
            return c.scores()[0]
    return None

def calculate_fix_time_days(vuln):
    """Вычисляет время исправления в днях (разница между modified и published)"""
    published = vuln.get("published")
    modified = vuln.get("modified")

    if not published or not modified:
        return None
    try:
        # Приводим даты к UTC для единообразия
        pub_date = datetime.fromisoformat(published.replace('Z', '+00:00'))
        mod_date = datetime.fromisoformat(modified.replace('Z', '+00:00'))

        # Вычисляем разницу в днях
        delta = mod_date - pub_date
        return delta.days
    except ValueError:
        return None

def process_ecosystem(ecosystem_name, url):
    """Основная функция для обработки одной экосистемы"""
    print(f"\n--- Обработка экосистемы: {ecosystem_name} ---")
    results = []

    # 1. Загружаем все уязвимости
    vulnerabilities = ECOSYSTEM_archive[ecosystem_name]
    total = len(vulnerabilities)
    print(f"Загружено {total} записей")

    # 2. Фильтруем и извлекаем данные
    for i, vuln in enumerate(vulnerabilities):
        if (i + 1) % 1000 == 0:
            print(f"Обработано {i+1}/{total} записей...")

        # Проверяем наличие severity
        severity_score = extract_cvss_severity(vuln)
        if severity_score is None:
            continue
        fix_time = calculate_fix_time_days(vuln)
        if "database_specific" in vuln:
          if "cwe_ids" in vuln["database_specific"]:
              for cwe in vuln["database_specific"]["cwe_ids"]:
                if cwe not in allCWE:
                  allCWE[cwe] = 0
                if cwe not in CWEmetricks:
                  CWEmetricks[cwe] = 0
                allCWE[cwe] += 1
                CWEmetricks[cwe] += fix_time * severity_score

        results.append({
            "id": vuln.get("id"),
            "ecosystem": ecosystem_name,
            "summary": vuln.get("summary", ""),
            "cvss_v3_score": severity_score,
            "fix_time_days": fix_time,
            "published": vuln.get("published"),
            "modified": vuln.get("modified"),
            "cwe_ids": vuln.get("database_specific",[])
        })

    print(f"Найдено записей с severity: {len(results)}")
    return results

if __name__ == "__main__":
    all_results = []

    # Обрабатываем каждую экосистему
    for name, url in ECOSYSTEMS.items():
        ecosystem_results = process_ecosystem(name, url)
        all_results.extend(ecosystem_results)

    # Сохраняем результат
    with open('vulnerabilities_analysis.json', 'w', encoding='utf-8') as f:
        json.dump(all_results, f, indent=2, ensure_ascii=False)

    print(f"\nГотово! Всего обработано записей с severity: {len(all_results)}")
    print("Результат сохранен в файл 'vulnerabilities_analysis.json'")

--- Обработка экосистемы: PyPI ---
Загружено 19564 записей
Обработано 1000/19564 записей...
Обработано 2000/19564 записей...
Обработано 3000/19564 записей...
Обработано 4000/19564 записей...
Обработано 5000/19564 записей...
Обработано 6000/19564 записей...
Обработано 7000/19564 записей...
Обработано 8000/19564 записей...
Обработано 9000/19564 записей...
Обработано 10000/19564 записей...
Обработано 11000/19564 записей...
Обработано 12000/19564 записей...
Обработано 13000/19564 записей...
Обработано 14000/19564 записей...
Обработано 15000/19564 записей...
Обработано 16000/19564 записей...
Обработано 17000/19564 записей...
Обработано 18000/19564 записей...
Обработано 19000/19564 записей...
Найдено записей с severity: 5419

--- Обработка экосистемы: npm ---
Загружено 218681 записей
Обработано 1000/218681 записей...
Обработано 2000/218681 записей...
Обработано 3000/218681 записей...
Обработано 4000/218681 записей...
Обработано 5000/218681 записей...
Обработано 6000/218681 записей...
Обработано 7000/218681 записей...
Обработано 8000/218681 записей...
Обработано 9000/218681 записей...
Обработано 10000/218681 записей...
Обработано 11000/218681 записей...
Обработано 12000/218681 записей...
Обработано 13000/218681 записей...
Обработано 14000/218681 записей...
Обработано 15000/218681 записей...
Обработано 16000/218681 записей...
Обработано 17000/218681 записей...
Обработано 18000/218681 записей...
Обработано 19000/218681 записей...
Обработано 20000/218681 записей...
Обработано 21000/218681 записей...
Обработано 22000/218681 записей...
Обработано 23000/218681 записей...
Обработано 24000/218681 записей...
Обработано 25000/218681 записей...
Обработано 26000/218681 записей...
Обработано 27000/218681 записей...
Обработано 28000/218681 записей...
Обработано 29000/218681 записей...
Обработано 30000/218681 записей...
Обработано 31000/218681 записей...
Обработано 32000/218681 записей...
Обработано 33000/218681 записей...
Обработано 34000/218681 записей...
Обработано 35000/218681 записей...
Обработано 36000/218681 записей...
Обработано 37000/218681 записей...
Обработано 38000/218681 записей...
Обработано 39000/218681 записей...
Обработано 40000/218681 записей...
Обработано 41000/218681 записей...
Обработано 42000/218681 записей...
Обработано 43000/218681 записей...
Обработано 44000/218681 записей...
Обработано 45000/218681 записей...
Обработано 46000/218681 записей...
Обработано 47000/218681 записей...
Обработано 48000/218681 записей...
Обработано 49000/218681 записей...
Обработано 50000/218681 записей...
Обработано 51000/218681 записей...
Обработано 52000/218681 записей...
Обработано 53000/218681 записей...
Обработано 54000/218681 записей...
Обработано 55000/218681 записей...
Обработано 56000/218681 записей...
Обработано 57000/218681 записей...
Обработано 58000/218681 записей...
Обработано 59000/218681 записей...
Обработано 60000/218681 записей...
Обработано 61000/218681 записей...
Обработано 62000/218681 записей...
Обработано 63000/218681 записей...
Обработано 64000/218681 записей...
Обработано 65000/218681 записей...
Обработано 66000/218681 записей...
Обработано 67000/218681 записей...
Обработано 68000/218681 записей...
Обработано 69000/218681 записей...
Обработано 70000/218681 записей...
Обработано 71000/218681 записей...
Обработано 72000/218681 записей...
Обработано 73000/218681 записей...
Обработано 74000/218681 записей...
Обработано 75000/218681 записей...
Обработано 76000/218681 записей...
Обработано 77000/218681 записей...
Обработано 78000/218681 записей...
Обработано 79000/218681 записей...
Обработано 80000/218681 записей...
Обработано 81000/218681 записей...
Обработано 82000/218681 записей...
Обработано 83000/218681 записей...
Обработано 84000/218681 записей...
Обработано 85000/218681 записей...
Обработано 86000/218681 записей...
Обработано 87000/218681 записей...
Обработано 88000/218681 записей...
Обработано 89000/218681 записей...
Обработано 90000/218681 записей...
Обработано 91000/218681 записей...
Обработано 92000/218681 записей...
Обработано 93000/218681 записей...
Обработано 94000/218681 записей...
Обработано 95000/218681 записей...
Обработано 96000/218681 записей...
Обработано 97000/218681 записей...
Обработано 98000/218681 записей...
Обработано 99000/218681 записей...
Обработано 100000/218681 записей...
Обработано 101000/218681 записей...
Обработано 102000/218681 записей...
Обработано 103000/218681 записей...
Обработано 104000/218681 записей...
Обработано 105000/218681 записей...
Обработано 106000/218681 записей...
Обработано 107000/218681 записей...
Обработано 108000/218681 записей...
Обработано 109000/218681 записей...
Обработано 110000/218681 записей...
Обработано 111000/218681 записей...
Обработано 112000/218681 записей...
Обработано 113000/218681 записей...
Обработано 114000/218681 записей...
Обработано 115000/218681 записей...
Обработано 116000/218681 записей...
Обработано 117000/218681 записей...
Обработано 118000/218681 записей...
Обработано 119000/218681 записей...
Обработано 120000/218681 записей...
Обработано 121000/218681 записей...
Обработано 122000/218681 записей...
Обработано 123000/218681 записей...
Обработано 124000/218681 записей...
Обработано 125000/218681 записей...
Обработано 126000/218681 записей...
Обработано 127000/218681 записей...
Обработано 128000/218681 записей...
Обработано 129000/218681 записей...
Обработано 130000/218681 записей...
Обработано 131000/218681 записей...
Обработано 132000/218681 записей...
Обработано 133000/218681 записей...
Обработано 134000/218681 записей...
Обработано 135000/218681 записей...
Обработано 136000/218681 записей...
Обработано 137000/218681 записей...
Обработано 138000/218681 записей...
Обработано 139000/218681 записей...
Обработано 140000/218681 записей...
Обработано 141000/218681 записей...
Обработано 142000/218681 записей...
Обработано 143000/218681 записей...
Обработано 144000/218681 записей...
Обработано 145000/218681 записей...
Обработано 146000/218681 записей...
Обработано 147000/218681 записей...
Обработано 148000/218681 записей...
Обработано 149000/218681 записей...
Обработано 150000/218681 записей...
Обработано 151000/218681 записей...
Обработано 152000/218681 записей...
Обработано 153000/218681 записей...
Обработано 154000/218681 записей...
Обработано 155000/218681 записей...
Обработано 156000/218681 записей...
Обработано 157000/218681 записей...
Обработано 158000/218681 записей...
Обработано 159000/218681 записей...
Обработано 160000/218681 записей...
Обработано 161000/218681 записей...
Обработано 162000/218681 записей...
Обработано 163000/218681 записей...
Обработано 164000/218681 записей...
Обработано 165000/218681 записей...
Обработано 166000/218681 записей...
Обработано 167000/218681 записей...
Обработано 168000/218681 записей...
Обработано 169000/218681 записей...
Обработано 170000/218681 записей...
Обработано 171000/218681 записей...
Обработано 172000/218681 записей...
Обработано 173000/218681 записей...
Обработано 174000/218681 записей...
Обработано 175000/218681 записей...
Обработано 176000/218681 записей...
Обработано 177000/218681 записей...
Обработано 178000/218681 записей...
Обработано 179000/218681 записей...
Обработано 180000/218681 записей...
Обработано 181000/218681 записей...
Обработано 182000/218681 записей...
Обработано 183000/218681 записей...
Обработано 184000/218681 записей...
Обработано 185000/218681 записей...
Обработано 186000/218681 записей...
Обработано 187000/218681 записей...
Обработано 188000/218681 записей...
Обработано 189000/218681 записей...
Обработано 190000/218681 записей...
Обработано 191000/218681 записей...
Обработано 192000/218681 записей...
Обработано 193000/218681 записей...
Обработано 194000/218681 записей...
Обработано 195000/218681 записей...
Обработано 196000/218681 записей...
Обработано 197000/218681 записей...
Обработано 198000/218681 записей...
Обработано 199000/218681 записей...
Обработано 200000/218681 записей...
Обработано 201000/218681 записей...
Обработано 202000/218681 записей...
Обработано 203000/218681 записей...
Обработано 204000/218681 записей...
Обработано 205000/218681 записей...
Обработано 206000/218681 записей...
Обработано 207000/218681 записей...
Обработано 208000/218681 записей...
Обработано 209000/218681 записей...
Обработано 210000/218681 записей...
Обработано 211000/218681 записей...
Обработано 212000/218681 записей...
Обработано 213000/218681 записей...
Обработано 214000/218681 записей...
Обработано 215000/218681 записей...
Обработано 216000/218681 записей...
Обработано 217000/218681 записей...
Обработано 218000/218681 записей...
Найдено записей с severity: 5457

--- Обработка экосистемы: Go ---
Загружено 6946 записей
Обработано 1000/6946 записей...
Обработано 2000/6946 записей...
Обработано 3000/6946 записей...
Обработано 4000/6946 записей...
Обработано 5000/6946 записей...
Обработано 6000/6946 записей...
Найдено записей с severity: 3656

Готово! Всего обработано записей с severity: 14532
Результат сохранен в файл 'vulnerabilities_analysis.json'

In [ ]:
allCWE

{'CWE-20': 933,
 'CWE-22': 1358,
 'CWE-73': 93,
 'CWE-94': 643,
 'CWE-434': 126,
 'CWE-669': 20,
 'CWE-444': 86,
 'CWE-200': 784,
 'CWE-79': 1790,
 'CWE-754': 86,
 'CWE-601': 336,
 'CWE-640': 15,
 'CWE-502': 413,
 'CWE-674': 96,
 'CWE-287': 384,
 'CWE-787': 238,
 'CWE-284': 375,
 'CWE-125': 260,
 'CWE-552': 42,
 'CWE-791': 13,
 'CWE-362': 121,
 'CWE-367': 91,
 'CWE-1270': 3,
 'CWE-617': 139,
 'CWE-400': 889,
 'CWE-918': 577,
 'CWE-611': 89,
 'CWE-190': 136,
 'CWE-409': 53,
 'CWE-704': 19,
 'CWE-755': 67,
 'CWE-789': 37,
 'CWE-777': 3,
 'CWE-193': 15,
 'CWE-416': 48,
 'CWE-122': 50,
 'CWE-323': 6,
 'CWE-693': 92,
 'CWE-306': 208,
 'CWE-78': 542,
 'CWE-639': 187,
 'CWE-862': 309,
 'CWE-369': 129,
 'CWE-250': 31,
 'CWE-311': 89,
 'CWE-322': 7,
 'CWE-770': 513,
 'CWE-77': 346,
 'CWE-772': 21,
 'CWE-319': 36,
 'CWE-377': 30,
 'CWE-863': 629,
 'CWE-201': 40,
 'CWE-209': 79,
 'CWE-67': 6,
 'CWE-424': 3,
 'CWE-532': 188,
 'CWE-185': 25,
 'CWE-59': 157,
 'CWE-345': 142,
 'CWE-426': 44,
 'CWE-829': 63,
 'CWE-352': 252,
 'CWE-1333': 314,
 'CWE-178': 28,
 'CWE-303': 23,
 'CWE-89': 337,
 'CWE-384': 44,
 'CWE-522': 111,
 'CWE-208': 74,
 'CWE-1395': 42,
 'CWE-295': 195,
 'CWE-285': 207,
 'CWE-942': 30,
 'CWE-476': 231,
 'CWE-269': 210,
 'CWE-682': 23,
 'CWE-237': 4,
 'CWE-347': 177,
 'CWE-835': 121,
 'CWE-120': 92,
 'CWE-401': 28,
 'CWE-404': 21,
 'CWE-29': 50,
 'CWE-74': 256,
 'CWE-290': 97,
 'CWE-113': 23,
 'CWE-1284': 39,
 'CWE-281': 33,
 'CWE-697': 46,
 'CWE-824': 32,
 'CWE-916': 13,
 'CWE-328': 23,
 'CWE-440': 16,
 'CWE-93': 42,
 'CWE-212': 28,
 'CWE-359': 23,
 'CWE-116': 89,
 'CWE-88': 79,
 'CWE-407': 28,
 'CWE-427': 34,
 'CWE-1336': 58,
 'CWE-680': 4,
 'CWE-326': 33,
 'CWE-327': 68,
 'CWE-131': 24,
 'CWE-203': 68,
 'CWE-204': 24,
 'CWE-913': 46,
 'CWE-613': 113,
 'CWE-457': 9,
 'CWE-312': 57,
 'CWE-602': 7,
 'CWE-87': 9,
 'CWE-643': 4,
 'CWE-119': 118,
 'CWE-420': 11,
 'CWE-620': 12,
 'CWE-36': 30,
 'CWE-732': 96,
 'CWE-346': 94,
 'CWE-776': 23,
 'CWE-95': 54,
 'CWE-425': 11,
 'CWE-667': 9,
 'CWE-833': 3,
 'CWE-90': 16,
 'CWE-1088': 9,
 'CWE-248': 65,
 'CWE-23': 71,
 'CWE-61': 51,
 'CWE-696': 13,
 'CWE-691': 4,
 'CWE-923': 6,
 'CWE-385': 17,
 'CWE-134': 14,
 'CWE-749': 27,
 'CWE-798': 43,
 'CWE-668': 121,
 'CWE-307': 68,
 'CWE-340': 8,
 'CWE-405': 12,
 'CWE-354': 30,
 'CWE-915': 110,
 'CWE-676': 2,
 'CWE-184': 102,
 'CWE-1295': 2,
 'CWE-76': 4,
 'CWE-25': 4,
 'CWE-590': 2,
 'CWE-289': 7,
 'CWE-336': 2,
 'CWE-75': 16,
 'CWE-670': 43,
 'CWE-410': 2,
 'CWE-908': 29,
 'CWE-506': 385,
 'CWE-1236': 15,
 'CWE-325': 9,
 'CWE-683': 6,
 'CWE-350': 16,
 'CWE-470': 11,
 'CWE-321': 23,
 'CWE-35': 14,
 'CWE-436': 50,
 'CWE-471': 21,
 'CWE-834': 20,
 'CWE-807': 29,
 'CWE-598': 15,
 'CWE-684': 2,
 'CWE-521': 26,
 'CWE-324': 7,
 'CWE-351': 8,
 'CWE-96': 3,
 'CWE-396': 4,
 'CWE-379': 8,
 'CWE-129': 43,
 'CWE-497': 22,
 'CWE-202': 8,
 'CWE-331': 21,
 'CWE-276': 86,
 'CWE-80': 53,
 'CWE-1188': 43,
 'CWE-330': 51,
 'CWE-524': 15,
 'CWE-83': 5,
 'CWE-256': 13,
 'CWE-707': 5,
 'CWE-294': 40,
 'CWE-526': 6,
 'CWE-130': 19,
 'CWE-12': 4,
 'CWE-475': 9,
 'CWE-121': 7,
 'CWE-1021': 17,
 'CWE-627': 7,
 'CWE-843': 58,
 'CWE-599': 7,
 'CWE-117': 30,
 'CWE-26': 5,
 'CWE-280': 21,
 'CWE-91': 22,
 'CWE-1321': 460,
 'CWE-115': 12,
 'CWE-1125': 2,
 'CWE-273': 3,
 'CWE-501': 13,
 'CWE-646': 6,
 'CWE-459': 9,
 'CWE-1385': 17,
 'CWE-213': 5,
 'CWE-539': 4,
 'CWE-763': 2,
 'CWE-565': 4,
 'CWE-253': 3,
 'CWE-394': 2,
 'CWE-15': 26,
 'CWE-41': 6,
 'CWE-488': 3,
 'CWE-283': 8,
 'CWE-338': 18,
 'CWE-681': 23,
 'CWE-453': 6,
 'CWE-1230': 3,
 'CWE-304': 5,
 'CWE-494': 13,
 'CWE-909': 6,
 'CWE-1286': 10,
 'CWE-664': 3,
 'CWE-665': 23,
 'CWE-266': 43,
 'CWE-1004': 15,
 'CWE-313': 2,
 'CWE-1287': 23,
 'CWE-277': 10,
 'CWE-358': 14,
 'CWE-922': 16,
 'CWE-140': 2,
 'CWE-274': 3,
 'CWE-1220': 16,
 'CWE-940': 10,
 'CWE-349': 17,
 'CWE-366': 4,
 'CWE-1023': 3,
 'CWE-1288': 3,
 'CWE-1100': 3,
 'CWE-300': 7,
 'CWE-756': 2,
 'CWE-830': 6,
 'CWE-480': 4,
 'CWE-233': 4,
 'CWE-378': 6,
 'CWE-415': 14,
 'CWE-288': 37,
 'CWE-610': 20,
 'CWE-647': 5,
 'CWE-252': 13,
 'CWE-606': 4,
 'CWE-779': 4,
 'CWE-1049': 2,
 'CWE-305': 19,
 'CWE-799': 12,
 'CWE-159': 2,
 'CWE-525': 6,
 'CWE-1283': 2,
 'CWE-527': 3,
 'CWE-943': 15,
 'CWE-150': 19,
 'CWE-653': 13,
 'CWE-1393': 4,
 'CWE-662': 8,
 'CWE-197': 3,
 'CWE-757': 4,
 'CWE-914': 2,
 'CWE-1256': 2,
 'CWE-1056': 2,
 'CWE-788': 2,
 'CWE-733': 2,
 'CWE-191': 8,
 'CWE-315': 3,
 'CWE-270': 2,
 'CWE-636': 18,
 'CWE-703': 27,
 'CWE-242': 2,
 'CWE-706': 33,
 'CWE-402': 5,
 'CWE-821': 2,
 'CWE-173': 5,
 'CWE-921': 3,
 'CWE-573': 3,
 'CWE-614': 13,
 'CWE-286': 4,
 'CWE-1112': 2,
 'CWE-123': 5,
 'CWE-282': 2,
 'CWE-259': 2,
 'CWE-187': 3,
 'CWE-170': 3,
 'CWE-673': 3,
 'CWE-441': 27,
 'CWE-214': 2,
 'CWE-648': 9,
 'CWE-1327': 4,
 'CWE-279': 4,
 'CWE-391': 2,
 'CWE-195': 3,
 'CWE-1241': 4,
 'CWE-329': 3,
 'CWE-547': 6,
 'CWE-657': 2,
 'CWE-460': 6,
 'CWE-841': 2,
 'CWE-1240': 4,
 'CWE-64': 6,
 'CWE-215': 5,
 'CWE-337': 5,
 'CWE-31': 3,
 'CWE-298': 3,
 'CWE-118': 2,
 'CWE-489': 3,
 'CWE-924': 4,
 'CWE-1022': 7,
 'CWE-183': 13,
 'CWE-641': 3,
 'CWE-176': 7,
 'CWE-395': 2,
 'CWE-332': 4,
 'CWE-694': 5,
 'CWE-433': 4,
 'CWE-912': 3,
 'CWE-180': 5,
 'CWE-241': 6,
 'CWE-24': 12,
 'CWE-261': 2,
 'CWE-690': 4,
 'CWE-672': 11,
 'CWE-1119': 1,
 'CWE-1254': 2,
 'CWE-50': 1,
 'CWE-1255': 1,
 'CWE-783': 1,
 'CWE-335': 3,
 'CWE-508': 1,
 'CWE-353': 3,
 'CWE-348': 5,
 'CWE-509': 1,
 'CWE-98': 2,
 'CWE-548': 4,
 'CWE-219': 2,
 'CWE-1392': 6,
 'CWE-428': 4,
 'CWE-1113': 1,
 'CWE-939': 1,
 'CWE-177': 6,
 'CWE-316': 1,
 'CWE-179': 1,
 'CWE-538': 6,
 'CWE-144': 1,
 'CWE-451': 4,
 'CWE-1341': 1,
 'CWE-541': 1,
 'CWE-624': 1,
 'CWE-27': 1,
 'CWE-790': 2,
 'CWE-127': 1,
 'CWE-364': 1,
 'CWE-564': 1,
 'CWE-154': 1,
 'CWE-226': 1,
 'CWE-99': 2,
 'CWE-1289': 8,
 'CWE-625': 1,
 'CWE-235': 1,
 'CWE-642': 2,
 'CWE-759': 3,
 'CWE-126': 3,
 'CWE-84': 2,
 'CWE-1391': 6,
 'CWE-1050': 3,
 'CWE-644': 5,
 'CWE-40': 1,
 'CWE-408': 3,
 'CWE-1259': 3,
 'CWE-472': 1,
 'CWE-1104': 1,
 'CWE-454': 1,
 'CWE-1320': 1,
 'CWE-1335': 1,
 'CWE-138': 1,
 'CWE-544': 1,
 'CWE-774': 1,
 'CWE-926': 1,
 'CWE-172': 2,
 'CWE-792': 1,
 'CWE-705': 1,
 'CWE-291': 1,
 'CWE-272': 1,
 'CWE-1285': 2,
 'CWE-626': 1,
 'CWE-1007': 1,
 'CWE-820': 2,
 'CWE-1314': 1,
 'CWE-156': 4,
 'CWE-228': 2,
 'CWE-192': 2,
 'CWE-1068': 1,
 'CWE-302': 2,
 'CWE-1038': 1,
 'CWE-271': 3,
 'CWE-229': 1,
 'CWE-299': 1,
 'CWE-1386': 1,
 'CWE-363': 5,
 'CWE-842': 3,
 'CWE-343': 2,
 'CWE-456': 1,
 'CWE-297': 2,
 'CWE-390': 2,
 'CWE-478': 1,
 'CWE-155': 2,
 'CWE-826': 1,
 'CWE-308': 1,
 'CWE-663': 1,
 'CWE-372': 1,
 'CWE-804': 1,
 'CWE-708': 1,
 'CWE-1108': 1,
 'CWE-296': 2,
 'CWE-268': 1,
 'CWE-419': 1,
 'CWE-263': 1,
 'CWE-595': 1,
 'CWE-692': 1,
 'CWE-1173': 1,
 'CWE-267': 1,
 'CWE-158': 1,
 'CWE-168': 1,
 'CWE-30': 1,
 'CWE-645': 1,
 'CWE-365': 1,
 'CWE-941': 1,
 'CWE-920': 1,
 'CWE-836': 1,
 'CWE-566': 1,
 'CWE-1390': 1,
 'CWE-549': 1,
 'CWE-495': 1,
 'CWE-403': 1}

In [ ]:
CWEmetricks

In [ ]:
import pandas as pd

In [ ]:
for cwe, count in allCWE.items():
  CWEmetricks[cwe] = CWEmetricks[cwe] / count

In [ ]:
firstCOL = "Насколько быстро экосистема экосистемы реагируют на данный тип проблемы"

In [ ]:
secondCOL = "Насколько быстро экосистема экосистемы реагируют на данный тип проблемы"

In [ ]:
data = pd.DataFrame({
    firstCOL : allCWE,
    secondCOL : CWEmetricks
    })

In [ ]:
data

          Насколько быстро экосистема экосистемы реагируют на данный тип проблемы
CWE-20                                          5571.233655
CWE-22                                          3387.350589
CWE-73                                           924.546237
CWE-94                                          4007.132193
CWE-434                                         3118.023016
...                                                     ...
CWE-566                                         1749.600000
CWE-1390                                          90.200000
CWE-549                                         1330.300000
CWE-495                                           58.500000
CWE-403                                         6312.400000

[448 rows x 1 columns]

In [ ]:
df_sorted = data.sort_values(by=secondCOL, ascending=False)

In [71]:
upstream_graph = {}   # Формат: { "ID": ["Upstream_ID_1", "Upstream_ID_2"] }
ecosystem_map = {}    # Формат: { "ID": "PyPI" } (чтобы знать, к кому относится)

In [73]:
import json
import requests
import zipfile
import io
import re
import pandas as pd
from datetime import datetime, timezone
from cvss import CVSS2, CVSS3, CVSS4

ECOSYSTEMS = {
    "PyPI": "https://osv-vulnerabilities.storage.googleapis.com/PyPI/all.zip",
    "npm": "https://osv-vulnerabilities.storage.googleapis.com/npm/all.zip",
    "Go": "https://osv-vulnerabilities.storage.googleapis.com/Go/all.zip"
}

def extract_cvss_severity(vuln):
    """Извлекает числовое значение из CVSS score"""
    severity_list = vuln.get("severity", [])
    for severity in severity_list:
        score_str = severity.get("score")
        match = re.search(r"(\d+\.?\d*)", score_str)
        if not match:
            continue
        if severity.get("type") == "CVSS_V4":
            c = CVSS4(severity.get("score"))
            return c.scores()[0]
        elif severity.get("type") == "CVSS_V3":
            c = CVSS3(severity.get("score"))
            return c.scores()[0]
        else:
            c = CVSS2(severity.get("score"))
            return c.scores()[0]
    return None

def calculate_fix_time_days(vuln):
    """Вычисляет время исправления в днях (разница между modified и published)"""
    published = vuln.get("published")
    modified = vuln.get("modified")

    if not published or not modified:
        return None
    try:
        pub_date = datetime.fromisoformat(published.replace('Z', '+00:00'))
        mod_date = datetime.fromisoformat(modified.replace('Z', '+00:00'))

        delta = mod_date - pub_date
        return delta.days
    except ValueError:
        return None

def process_ecosystem(ecosystem_name, url):
    """Основная функция для обработки одной экосистемы"""
    print(f"\n--- Обработка экосистемы: {ecosystem_name} ---")
    results = []

    # Словари теперь локальные для каждой экосистемы
    ecosystem_cwe_count = {}
    ecosystem_cwe_metric = {}

    # 1. Скачиваем и распаковываем данные в памяти
    print(f"Скачивание архива для {ecosystem_name}...")
    response = requests.get(url)
    vulnerabilities = []
    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        for filename in z.namelist():
            if filename.endswith('.json'):
                with z.open(filename) as f:
                    vulnerabilities.append(json.load(f))

    total = len(vulnerabilities)
    print(f"Загружено {total} записей")

    # 2. Фильтруем и извлекаем данные
    for i, vuln in enumerate(vulnerabilities):
        if (i + 1) % 1000 == 0:
            print(f"Обработано {i+1}/{total} записей...")

        vuln_id = vuln.get("id")
        ecosystems = ecosystem_name
        ecosystem_map[vuln_id] = ecosystem_name

        upstreams = vuln.get("upstream", [])
        upstream_graph[vuln_id] = upstreams

        severity_score = extract_cvss_severity(vuln)
        if severity_score is None:
            continue

        fix_time = calculate_fix_time_days(vuln)

        # Обновляем словари только для текущей экосистемы
        if "database_specific" in vuln and "cwe_ids" in vuln["database_specific"]:
            for cwe in vuln["database_specific"]["cwe_ids"]:
                if cwe not in ecosystem_cwe_count:
                    ecosystem_cwe_count[cwe] = 0
                    ecosystem_cwe_metric[cwe] = 0

                ecosystem_cwe_count[cwe] += 1

                # Защита от ошибки, если fix_time == None
                if fix_time is not None:
                    ecosystem_cwe_metric[cwe] += fix_time * severity_score

        results.append({
            "id": vuln.get("id"),
            "ecosystem": ecosystem_name,
            "summary": vuln.get("summary", ""),
            "cvss_v3_score": severity_score,
            "fix_time_days": fix_time,
            "published": vuln.get("published"),
            "modified": vuln.get("modified"),
            "cwe_ids": vuln.get("database_specific", {}).get("cwe_ids", [])
        })

    print(f"Найдено записей с severity: {len(results)}")
    # Возвращаем результаты и словари для пандаса
    return results, ecosystem_cwe_count, ecosystem_cwe_metric
if __name__ == "__main__":
    all_results = []

    # Словари для сбора данных под pandas
    all_counts_for_df = {}
    all_metrics_for_df = {}

    for name, url in ECOSYSTEMS.items():
        ecosystem_results, count_dict, metric_dict = process_ecosystem(name, url)
        all_results.extend(ecosystem_results)
        for cwe, count in count_dict.items():
          metric_dict[cwe] /= count
        # Сохраняем словари, задавая названия будущих колонок
        all_counts_for_df[f"{name}_Count"] = count_dict
        all_metrics_for_df[f"{name}_Metric"] = metric_dict

    # Сохраняем сырые json результаты
    # with open('vulnerabilities_analysis.json', 'w', encoding='utf-8') as f:
    #     json.dump(all_results, f, indent=2, ensure_ascii=False)

    # --- Блок Pandas ---
    print("\n--- Формирование pandas таблицы ---")
    # Создаем два DataFrame из собранных словарей
    df_counts = pd.DataFrame(all_counts_for_df)
    df_metrics = pd.DataFrame(all_metrics_for_df)

    # Объединяем по индексу (CWE). axis=1 означает соединение столбцов.
    # Если в какой-то экосистеме нет конкретного CWE, ставим 0
    df_final = pd.concat([df_counts, df_metrics], axis=1).fillna(0)

    # Опционально: сортируем столбцы для красоты (PyPI_Count, PyPI_Metric, npm_Count...)
    columns_order = []
    for name in ECOSYSTEMS.keys():
        columns_order.extend([f"{name}_Count", f"{name}_Metric"])
    df_final = df_final[columns_order]

    # Выводим первые строки и сохраняем в CSV
    print(df_final.head())
    df_final.to_csv("cwe_ecosystems_summary.csv")
    print("\nГотово! Статистика по CWE сохранена в 'cwe_ecosystems_summary.csv'")

--- Обработка экосистемы: PyPI ---
Скачивание архива для PyPI...
Загружено 19564 записей
Обработано 1000/19564 записей...
Обработано 2000/19564 записей...
Обработано 3000/19564 записей...
Обработано 4000/19564 записей...
Обработано 5000/19564 записей...
Обработано 6000/19564 записей...
Обработано 7000/19564 записей...
Обработано 8000/19564 записей...
Обработано 9000/19564 записей...
Обработано 10000/19564 записей...
Обработано 11000/19564 записей...
Обработано 12000/19564 записей...
Обработано 13000/19564 записей...
Обработано 14000/19564 записей...
Обработано 15000/19564 записей...
Обработано 16000/19564 записей...
Обработано 17000/19564 записей...
Обработано 18000/19564 записей...
Обработано 19000/19564 записей...
Найдено записей с severity: 5419

--- Обработка экосистемы: npm ---
Скачивание архива для npm...
Загружено 218692 записей
Обработано 1000/218692 записей...
Обработано 2000/218692 записей...
Обработано 3000/218692 записей...
Обработано 4000/218692 записей...
Обработано 5000/218692 записей...
Обработано 6000/218692 записей...
Обработано 7000/218692 записей...
Обработано 8000/218692 записей...
Обработано 9000/218692 записей...
Обработано 10000/218692 записей...
Обработано 11000/218692 записей...
Обработано 12000/218692 записей...
Обработано 13000/218692 записей...
Обработано 14000/218692 записей...
Обработано 15000/218692 записей...
Обработано 16000/218692 записей...
Обработано 17000/218692 записей...
Обработано 18000/218692 записей...
Обработано 19000/218692 записей...
Обработано 20000/218692 записей...
Обработано 21000/218692 записей...
Обработано 22000/218692 записей...
Обработано 23000/218692 записей...
Обработано 24000/218692 записей...
Обработано 25000/218692 записей...
Обработано 26000/218692 записей...
Обработано 27000/218692 записей...
Обработано 28000/218692 записей...
Обработано 29000/218692 записей...
Обработано 30000/218692 записей...
Обработано 31000/218692 записей...
Обработано 32000/218692 записей...
Обработано 33000/218692 записей...
Обработано 34000/218692 записей...
Обработано 35000/218692 записей...
Обработано 36000/218692 записей...
Обработано 37000/218692 записей...
Обработано 38000/218692 записей...
Обработано 39000/218692 записей...
Обработано 40000/218692 записей...
Обработано 41000/218692 записей...
Обработано 42000/218692 записей...
Обработано 43000/218692 записей...
Обработано 44000/218692 записей...
Обработано 45000/218692 записей...
Обработано 46000/218692 записей...
Обработано 47000/218692 записей...
Обработано 48000/218692 записей...
Обработано 49000/218692 записей...
Обработано 50000/218692 записей...
Обработано 51000/218692 записей...
Обработано 52000/218692 записей...
Обработано 53000/218692 записей...
Обработано 54000/218692 записей...
Обработано 55000/218692 записей...
Обработано 56000/218692 записей...
Обработано 57000/218692 записей...
Обработано 58000/218692 записей...
Обработано 59000/218692 записей...
Обработано 60000/218692 записей...
Обработано 61000/218692 записей...
Обработано 62000/218692 записей...
Обработано 63000/218692 записей...
Обработано 64000/218692 записей...
Обработано 65000/218692 записей...
Обработано 66000/218692 записей...
Обработано 67000/218692 записей...
Обработано 68000/218692 записей...
Обработано 69000/218692 записей...
Обработано 70000/218692 записей...
Обработано 71000/218692 записей...
Обработано 72000/218692 записей...
Обработано 73000/218692 записей...
Обработано 74000/218692 записей...
Обработано 75000/218692 записей...
Обработано 76000/218692 записей...
Обработано 77000/218692 записей...
Обработано 78000/218692 записей...
Обработано 79000/218692 записей...
Обработано 80000/218692 записей...
Обработано 81000/218692 записей...
Обработано 82000/218692 записей...
Обработано 83000/218692 записей...
Обработано 84000/218692 записей...
Обработано 85000/218692 записей...
Обработано 86000/218692 записей...
Обработано 87000/218692 записей...
Обработано 88000/218692 записей...
Обработано 89000/218692 записей...
Обработано 90000/218692 записей...
Обработано 91000/218692 записей...
Обработано 92000/218692 записей...
Обработано 93000/218692 записей...
Обработано 94000/218692 записей...
Обработано 95000/218692 записей...
Обработано 96000/218692 записей...
Обработано 97000/218692 записей...
Обработано 98000/218692 записей...
Обработано 99000/218692 записей...
Обработано 100000/218692 записей...
Обработано 101000/218692 записей...
Обработано 102000/218692 записей...
Обработано 103000/218692 записей...
Обработано 104000/218692 записей...
Обработано 105000/218692 записей...
Обработано 106000/218692 записей...
Обработано 107000/218692 записей...
Обработано 108000/218692 записей...
Обработано 109000/218692 записей...
Обработано 110000/218692 записей...
Обработано 111000/218692 записей...
Обработано 112000/218692 записей...
Обработано 113000/218692 записей...
Обработано 114000/218692 записей...
Обработано 115000/218692 записей...
Обработано 116000/218692 записей...
Обработано 117000/218692 записей...
Обработано 118000/218692 записей...
Обработано 119000/218692 записей...
Обработано 120000/218692 записей...
Обработано 121000/218692 записей...
Обработано 122000/218692 записей...
Обработано 123000/218692 записей...
Обработано 124000/218692 записей...
Обработано 125000/218692 записей...
Обработано 126000/218692 записей...
Обработано 127000/218692 записей...
Обработано 128000/218692 записей...
Обработано 129000/218692 записей...
Обработано 130000/218692 записей...
Обработано 131000/218692 записей...
Обработано 132000/218692 записей...
Обработано 133000/218692 записей...
Обработано 134000/218692 записей...
Обработано 135000/218692 записей...
Обработано 136000/218692 записей...
Обработано 137000/218692 записей...
Обработано 138000/218692 записей...
Обработано 139000/218692 записей...
Обработано 140000/218692 записей...
Обработано 141000/218692 записей...
Обработано 142000/218692 записей...
Обработано 143000/218692 записей...
Обработано 144000/218692 записей...
Обработано 145000/218692 записей...
Обработано 146000/218692 записей...
Обработано 147000/218692 записей...
Обработано 148000/218692 записей...
Обработано 149000/218692 записей...
Обработано 150000/218692 записей...
Обработано 151000/218692 записей...
Обработано 152000/218692 записей...
Обработано 153000/218692 записей...
Обработано 154000/218692 записей...
Обработано 155000/218692 записей...
Обработано 156000/218692 записей...
Обработано 157000/218692 записей...
Обработано 158000/218692 записей...
Обработано 159000/218692 записей...
Обработано 160000/218692 записей...
Обработано 161000/218692 записей...
Обработано 162000/218692 записей...
Обработано 163000/218692 записей...
Обработано 164000/218692 записей...
Обработано 165000/218692 записей...
Обработано 166000/218692 записей...
Обработано 167000/218692 записей...
Обработано 168000/218692 записей...
Обработано 169000/218692 записей...
Обработано 170000/218692 записей...
Обработано 171000/218692 записей...
Обработано 172000/218692 записей...
Обработано 173000/218692 записей...
Обработано 174000/218692 записей...
Обработано 175000/218692 записей...
Обработано 176000/218692 записей...
Обработано 177000/218692 записей...
Обработано 178000/218692 записей...
Обработано 179000/218692 записей...
Обработано 180000/218692 записей...
Обработано 181000/218692 записей...
Обработано 182000/218692 записей...
Обработано 183000/218692 записей...
Обработано 184000/218692 записей...
Обработано 185000/218692 записей...
Обработано 186000/218692 записей...
Обработано 187000/218692 записей...
Обработано 188000/218692 записей...
Обработано 189000/218692 записей...
Обработано 190000/218692 записей...
Обработано 191000/218692 записей...
Обработано 192000/218692 записей...
Обработано 193000/218692 записей...
Обработано 194000/218692 записей...
Обработано 195000/218692 записей...
Обработано 196000/218692 записей...
Обработано 197000/218692 записей...
Обработано 198000/218692 записей...
Обработано 199000/218692 записей...
Обработано 200000/218692 записей...
Обработано 201000/218692 записей...
Обработано 202000/218692 записей...
Обработано 203000/218692 записей...
Обработано 204000/218692 записей...
Обработано 205000/218692 записей...
Обработано 206000/218692 записей...
Обработано 207000/218692 записей...
Обработано 208000/218692 записей...
Обработано 209000/218692 записей...
Обработано 210000/218692 записей...
Обработано 211000/218692 записей...
Обработано 212000/218692 записей...
Обработано 213000/218692 записей...
Обработано 214000/218692 записей...
Обработано 215000/218692 записей...
Обработано 216000/218692 записей...
Обработано 217000/218692 записей...
Обработано 218000/218692 записей...
Найдено записей с severity: 5457

--- Обработка экосистемы: Go ---
Скачивание архива для Go...
Загружено 6946 записей
Обработано 1000/6946 записей...
Обработано 2000/6946 записей...
Обработано 3000/6946 записей...
Обработано 4000/6946 записей...
Обработано 5000/6946 записей...
Обработано 6000/6946 записей...
Найдено записей с severity: 3656

--- Формирование pandas таблицы ---
         PyPI_Count  PyPI_Metric  npm_Count   npm_Metric  Go_Count  \
CWE-20        280.0  5986.705714      196.0  5840.180102     177.0
CWE-22        348.0  2361.149425      402.0  5616.242040     260.0
CWE-73         28.0   852.039286       19.0   713.215789      18.0
CWE-94        190.0  3804.079474      224.0  4649.268304      39.0
CWE-434        33.0  3204.196970       40.0  3576.372500      20.0

           Go_Metric
CWE-20   3958.929379
CWE-22   2688.203077
CWE-73   1373.194444
CWE-94   2297.428205
CWE-434  1916.950000

Готово! Статистика по CWE сохранена в 'cwe_ecosystems_summary.csv'

In [ ]:
df_pypi_sorted_by_count = df_final.sort_values(by="PyPI_Count", ascending=False)

In [ ]:
df_npm_sorted_by_count = df_final.sort_values(by="npm_Count", ascending=False)

In [ ]:
df_go_sorted_by_count = df_final.sort_values(by="Go_Count", ascending=False)

In [ ]:
df_pypi_sorted_by_count.head(15)["PyPI_Count"]

CWE-79     441.0
CWE-22     348.0
CWE-20     280.0
CWE-200    210.0
CWE-400    198.0
CWE-94     190.0
CWE-502    188.0
CWE-918    147.0
CWE-770    130.0
CWE-787    109.0
CWE-125    109.0
CWE-863    102.0
CWE-601    100.0
CWE-78      99.0
CWE-89      99.0
Name: PyPI_Count, dtype: float64

In [ ]:
import csv
import io
import requests

def load_cwe_dictionary():
    """Скачивает справочник CWE и возвращает словарь для маппинга"""
    print("Загрузка официального справочника CWE от MITRE...")
    # View 1000 - это самый полный список (Research Concepts)
    url = "https://cwe.mitre.org/data/csv/1000.csv.zip"

    response = requests.get(url)
    cwe_dict = {}

    with zipfile.ZipFile(io.BytesIO(response.content)) as z:
        # Внутри архива лежит файл 1000.csv
        with z.open('1000.csv') as f:
            # Читаем CSV
            csv_data = f.read().decode('utf-8')
            reader = csv.reader(io.StringIO(csv_data))

            headers = next(reader)
            # Индексы колонок в CSV: 0 - ID, 1 - Name, 2 - Abstraction (уровень)
            for row in reader:
                if len(row) > 2:
                    cwe_id = f"CWE-{row[0]}"
                    cwe_name = row[1]
                    cwe_dict[cwe_id] = cwe_name

    print(f"Загружено {len(cwe_dict)} описаний CWE.")
    return cwe_dict

In [ ]:
cwe_dict = load_cwe_dictionary()

Загрузка официального справочника CWE от MITRE...
Загружено 944 описаний CWE.

In [ ]:
cwe_dict

{'CWE-5': 'J2EE Misconfiguration: Data Transmission Without Encryption',
 'CWE-6': 'J2EE Misconfiguration: Insufficient Session-ID Length',
 'CWE-7': 'J2EE Misconfiguration: Missing Custom Error Page',
 'CWE-8': 'J2EE Misconfiguration: Entity Bean Declared Remote',
 'CWE-9': 'J2EE Misconfiguration: Weak Access Permissions for EJB Methods',
 'CWE-11': 'ASP.NET Misconfiguration: Creating Debug Binary',
 'CWE-12': 'ASP.NET Misconfiguration: Missing Custom Error Page',
 'CWE-13': 'ASP.NET Misconfiguration: Password in Configuration File',
 'CWE-14': 'Compiler Removal of Code to Clear Buffers',
 'CWE-15': 'External Control of System or Configuration Setting',
 'CWE-20': 'Improper Input Validation',
 'CWE-22': "Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')",
 'CWE-23': 'Relative Path Traversal',
 'CWE-24': "Path Traversal: '../filedir'",
 'CWE-25': "Path Traversal: '/../filedir'",
 'CWE-26': "Path Traversal: '/dir/../filename'",
 'CWE-27': "Path Traversal: 'dir/../../filename'",
 'CWE-28': "Path Traversal: '..filedir'",
 'CWE-29': "Path Traversal: '..filename'",
 'CWE-30': "Path Traversal: 'dir..filename'",
 'CWE-31': "Path Traversal: 'dir....filename'",
 'CWE-32': "Path Traversal: '...' (Triple Dot)",
 'CWE-33': "Path Traversal: '....' (Multiple Dot)",
 'CWE-34': "Path Traversal: '....//'",
 'CWE-35': "Path Traversal: '.../...//'",
 'CWE-36': 'Absolute Path Traversal',
 'CWE-37': "Path Traversal: '/absolute/pathname/here'",
 'CWE-38': "Path Traversal: 'absolutepathnamehere'",
 'CWE-39': "Path Traversal: 'C:dirname'",
 'CWE-40': "Path Traversal: 'UNCsharename' (Windows UNC Share)",
 'CWE-41': 'Improper Resolution of Path Equivalence',
 'CWE-42': "Path Equivalence: 'filename.' (Trailing Dot)",
 'CWE-43': "Path Equivalence: 'filename....' (Multiple Trailing Dot)",
 'CWE-44': "Path Equivalence: 'file.name' (Internal Dot)",
 'CWE-45': "Path Equivalence: 'file...name' (Multiple Internal Dot)",
 'CWE-46': "Path Equivalence: 'filename ' (Trailing Space)",
 'CWE-47': "Path Equivalence: ' filename' (Leading Space)",
 'CWE-48': "Path Equivalence: 'file name' (Internal Whitespace)",
 'CWE-49': "Path Equivalence: 'filename/' (Trailing Slash)",
 'CWE-50': "Path Equivalence: '//multiple/leading/slash'",
 'CWE-51': "Path Equivalence: '/multiple//internal/slash'",
 'CWE-52': "Path Equivalence: '/multiple/trailing/slash//'",
 'CWE-53': "Path Equivalence: 'multipleinternalbackslash'",
 'CWE-54': "Path Equivalence: 'filedir' (Trailing Backslash)",
 'CWE-55': "Path Equivalence: '/./' (Single Dot Directory)",
 'CWE-56': "Path Equivalence: 'filedir*' (Wildcard)",
 'CWE-57': "Path Equivalence: 'fakedir/../realdir/filename'",
 'CWE-58': 'Path Equivalence: Windows 8.3 Filename',
 'CWE-59': "Improper Link Resolution Before File Access ('Link Following')",
 'CWE-61': 'UNIX Symbolic Link (Symlink) Following',
 'CWE-62': 'UNIX Hard Link',
 'CWE-64': 'Windows Shortcut Following (.LNK)',
 'CWE-65': 'Windows Hard Link',
 'CWE-66': 'Improper Handling of File Names that Identify Virtual Resources',
 'CWE-67': 'Improper Handling of Windows Device Names',
 'CWE-69': 'Improper Handling of Windows ::DATA Alternate Data Stream',
 'CWE-72': 'Improper Handling of Apple HFS+ Alternate Data Stream Path',
 'CWE-73': 'External Control of File Name or Path',
 'CWE-74': "Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')",
 'CWE-75': 'Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)',
 'CWE-76': 'Improper Neutralization of Equivalent Special Elements',
 'CWE-77': "Improper Neutralization of Special Elements used in a Command ('Command Injection')",
 'CWE-78': "Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')",
 'CWE-79': "Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')",
 'CWE-80': 'Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)',
 'CWE-81': 'Improper Neutralization of Script in an Error Message Web Page',
 'CWE-82': 'Improper Neutralization of Script in Attributes of IMG Tags in a Web Page',
 'CWE-83': 'Improper Neutralization of Script in Attributes in a Web Page',
 'CWE-84': 'Improper Neutralization of Encoded URI Schemes in a Web Page',
 'CWE-85': 'Doubled Character XSS Manipulations',
 'CWE-86': 'Improper Neutralization of Invalid Characters in Identifiers in Web Pages',
 'CWE-87': 'Improper Neutralization of Alternate XSS Syntax',
 'CWE-88': "Improper Neutralization of Argument Delimiters in a Command ('Argument Injection')",
 'CWE-89': "Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')",
 'CWE-90': "Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')",
 'CWE-91': 'XML Injection (aka Blind XPath Injection)',
 'CWE-93': "Improper Neutralization of CRLF Sequences ('CRLF Injection')",
 'CWE-94': "Improper Control of Generation of Code ('Code Injection')",
 'CWE-95': "Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')",
 'CWE-96': "Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection')",
 'CWE-97': 'Improper Neutralization of Server-Side Includes (SSI) Within a Web Page',
 'CWE-98': "Improper Control of Filename for Include/Require Statement in PHP Program ('PHP Remote File Inclusion')",
 'CWE-99': "Improper Control of Resource Identifiers ('Resource Injection')",
 'CWE-102': 'Struts: Duplicate Validation Forms',
 'CWE-103': 'Struts: Incomplete validate() Method Definition',
 'CWE-104': 'Struts: Form Bean Does Not Extend Validation Class',
 'CWE-105': 'Struts: Form Field Without Validator',
 'CWE-106': 'Struts: Plug-in Framework not in Use',
 'CWE-107': 'Struts: Unused Validation Form',
 'CWE-108': 'Struts: Unvalidated Action Form',
 'CWE-109': 'Struts: Validator Turned Off',
 'CWE-110': 'Struts: Validator Without Form Field',
 'CWE-111': 'Direct Use of Unsafe JNI',
 'CWE-112': 'Missing XML Validation',
 'CWE-113': "Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Request/Response Splitting')",
 'CWE-114': 'Process Control',
 'CWE-115': 'Misinterpretation of Input',
 'CWE-116': 'Improper Encoding or Escaping of Output',
 'CWE-117': 'Improper Output Neutralization for Logs',
 'CWE-118': "Incorrect Access of Indexable Resource ('Range Error')",
 'CWE-119': 'Improper Restriction of Operations within the Bounds of a Memory Buffer',
 'CWE-120': "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')",
 'CWE-121': 'Stack-based Buffer Overflow',
 'CWE-122': 'Heap-based Buffer Overflow',
 'CWE-123': 'Write-what-where Condition',
 'CWE-124': "Buffer Underwrite ('Buffer Underflow')",
 'CWE-125': 'Out-of-bounds Read',
 'CWE-126': 'Buffer Over-read',
 'CWE-127': 'Buffer Under-read',
 'CWE-128': 'Wrap-around Error',
 'CWE-129': 'Improper Validation of Array Index',
 'CWE-130': 'Improper Handling of Length Parameter Inconsistency',
 'CWE-131': 'Incorrect Calculation of Buffer Size',
 'CWE-134': 'Use of Externally-Controlled Format String',
 'CWE-135': 'Incorrect Calculation of Multi-Byte String Length',
 'CWE-138': 'Improper Neutralization of Special Elements',
 'CWE-140': 'Improper Neutralization of Delimiters',
 'CWE-141': 'Improper Neutralization of Parameter/Argument Delimiters',
 'CWE-142': 'Improper Neutralization of Value Delimiters',
 'CWE-143': 'Improper Neutralization of Record Delimiters',
 'CWE-144': 'Improper Neutralization of Line Delimiters',
 'CWE-145': 'Improper Neutralization of Section Delimiters',
 'CWE-146': 'Improper Neutralization of Expression/Command Delimiters',
 'CWE-147': 'Improper Neutralization of Input Terminators',
 'CWE-148': 'Improper Neutralization of Input Leaders',
 'CWE-149': 'Improper Neutralization of Quoting Syntax',
 'CWE-150': 'Improper Neutralization of Escape, Meta, or Control Sequences',
 'CWE-151': 'Improper Neutralization of Comment Delimiters',
 'CWE-152': 'Improper Neutralization of Macro Symbols',
 'CWE-153': 'Improper Neutralization of Substitution Characters',
 'CWE-154': 'Improper Neutralization of Variable Name Delimiters',
 'CWE-155': 'Improper Neutralization of Wildcards or Matching Symbols',
 'CWE-156': 'Improper Neutralization of Whitespace',
 'CWE-157': 'Failure to Sanitize Paired Delimiters',
 'CWE-158': 'Improper Neutralization of Null Byte or NUL Character',
 'CWE-159': 'Improper Handling of Invalid Use of Special Elements',
 'CWE-160': 'Improper Neutralization of Leading Special Elements',
 'CWE-161': 'Improper Neutralization of Multiple Leading Special Elements',
 'CWE-162': 'Improper Neutralization of Trailing Special Elements',
 'CWE-163': 'Improper Neutralization of Multiple Trailing Special Elements',
 'CWE-164': 'Improper Neutralization of Internal Special Elements',
 'CWE-165': 'Improper Neutralization of Multiple Internal Special Elements',
 'CWE-166': 'Improper Handling of Missing Special Element',
 'CWE-167': 'Improper Handling of Additional Special Element',
 'CWE-168': 'Improper Handling of Inconsistent Special Elements',
 'CWE-170': 'Improper Null Termination',
 'CWE-172': 'Encoding Error',
 'CWE-173': 'Improper Handling of Alternate Encoding',
 'CWE-174': 'Double Decoding of the Same Data',
 'CWE-175': 'Improper Handling of Mixed Encoding',
 'CWE-176': 'Improper Handling of Unicode Encoding',
 'CWE-177': 'Improper Handling of URL Encoding (Hex Encoding)',
 'CWE-178': 'Improper Handling of Case Sensitivity',
 'CWE-179': 'Incorrect Behavior Order: Early Validation',
 'CWE-180': 'Incorrect Behavior Order: Validate Before Canonicalize',
 'CWE-181': 'Incorrect Behavior Order: Validate Before Filter',
 'CWE-182': 'Collapse of Data into Unsafe Value',
 'CWE-183': 'Permissive List of Allowed Inputs',
 'CWE-184': 'Incomplete List of Disallowed Inputs',
 'CWE-185': 'Incorrect Regular Expression',
 'CWE-186': 'Overly Restrictive Regular Expression',
 'CWE-187': 'Partial String Comparison',
 'CWE-188': 'Reliance on Data/Memory Layout',
 'CWE-190': 'Integer Overflow or Wraparound',
 'CWE-191': 'Integer Underflow (Wrap or Wraparound)',
 'CWE-192': 'Integer Coercion Error',
 'CWE-193': 'Off-by-one Error',
 'CWE-194': 'Unexpected Sign Extension',
 'CWE-195': 'Signed to Unsigned Conversion Error',
 'CWE-196': 'Unsigned to Signed Conversion Error',
 'CWE-197': 'Numeric Truncation Error',
 'CWE-198': 'Use of Incorrect Byte Ordering',
 'CWE-200': 'Exposure of Sensitive Information to an Unauthorized Actor',
 'CWE-201': 'Insertion of Sensitive Information Into Sent Data',
 'CWE-202': 'Exposure of Sensitive Information Through Data Queries',
 'CWE-203': 'Observable Discrepancy',
 'CWE-204': 'Observable Response Discrepancy',
 'CWE-205': 'Observable Behavioral Discrepancy',
 'CWE-206': 'Observable Internal Behavioral Discrepancy',
 'CWE-207': 'Observable Behavioral Discrepancy With Equivalent Products',
 'CWE-208': 'Observable Timing Discrepancy',
 'CWE-209': 'Generation of Error Message Containing Sensitive Information',
 'CWE-210': 'Self-generated Error Message Containing Sensitive Information',
 'CWE-211': 'Externally-Generated Error Message Containing Sensitive Information',
 'CWE-212': 'Improper Removal of Sensitive Information Before Storage or Transfer',
 'CWE-213': 'Exposure of Sensitive Information Due to Incompatible Policies',
 'CWE-214': 'Invocation of Process Using Visible Sensitive Information',
 'CWE-215': 'Insertion of Sensitive Information Into Debugging Code',
 'CWE-219': 'Storage of File with Sensitive Data Under Web Root',
 'CWE-220': 'Storage of File With Sensitive Data Under FTP Root',
 'CWE-221': 'Information Loss or Omission',
 'CWE-222': 'Truncation of Security-relevant Information',
 'CWE-223': 'Omission of Security-relevant Information',
 'CWE-224': 'Obscured Security-relevant Information by Alternate Name',
 'CWE-226': 'Sensitive Information in Resource Not Removed Before Reuse',
 'CWE-228': 'Improper Handling of Syntactically Invalid Structure',
 'CWE-229': 'Improper Handling of Values',
 'CWE-230': 'Improper Handling of Missing Values',
 'CWE-231': 'Improper Handling of Extra Values',
 'CWE-232': 'Improper Handling of Undefined Values',
 'CWE-233': 'Improper Handling of Parameters',
 'CWE-234': 'Failure to Handle Missing Parameter',
 'CWE-235': 'Improper Handling of Extra Parameters',
 'CWE-236': 'Improper Handling of Undefined Parameters',
 'CWE-237': 'Improper Handling of Structural Elements',
 'CWE-238': 'Improper Handling of Incomplete Structural Elements',
 'CWE-239': 'Failure to Handle Incomplete Element',
 'CWE-240': 'Improper Handling of Inconsistent Structural Elements',
 'CWE-241': 'Improper Handling of Unexpected Data Type',
 'CWE-242': 'Use of Inherently Dangerous Function',
 'CWE-243': 'Creation of chroot Jail Without Changing Working Directory',
 'CWE-244': "Improper Clearing of Heap Memory Before Release ('Heap Inspection')",
 'CWE-245': 'J2EE Bad Practices: Direct Management of Connections',
 'CWE-246': 'J2EE Bad Practices: Direct Use of Sockets',
 'CWE-248': 'Uncaught Exception',
 'CWE-250': 'Execution with Unnecessary Privileges',
 'CWE-252': 'Unchecked Return Value',
 'CWE-253': 'Incorrect Check of Function Return Value',
 'CWE-256': 'Plaintext Storage of a Password',
 'CWE-257': 'Storing Passwords in a Recoverable Format',
 'CWE-258': 'Empty Password in Configuration File',
 'CWE-259': 'Use of Hard-coded Password',
 'CWE-260': 'Password in Configuration File',
 'CWE-261': 'Weak Encoding for Password',
 'CWE-262': 'Not Using Password Aging',
 'CWE-263': 'Password Aging with Long Expiration',
 'CWE-266': 'Incorrect Privilege Assignment',
 'CWE-267': 'Privilege Defined With Unsafe Actions',
 'CWE-268': 'Privilege Chaining',
 'CWE-269': 'Improper Privilege Management',
 'CWE-270': 'Privilege Context Switching Error',
 'CWE-271': 'Privilege Dropping / Lowering Errors',
 'CWE-272': 'Least Privilege Violation',
 'CWE-273': 'Improper Check for Dropped Privileges',
 'CWE-274': 'Improper Handling of Insufficient Privileges',
 'CWE-276': 'Incorrect Default Permissions',
 'CWE-277': 'Insecure Inherited Permissions',
 'CWE-278': 'Insecure Preserved Inherited Permissions',
 'CWE-279': 'Incorrect Execution-Assigned Permissions',
 'CWE-280': 'Improper Handling of Insufficient Permissions or Privileges',
 'CWE-281': 'Improper Preservation of Permissions',
 'CWE-282': 'Improper Ownership Management',
 'CWE-283': 'Unverified Ownership',
 'CWE-284': 'Improper Access Control',
 'CWE-285': 'Improper Authorization',
 'CWE-286': 'Incorrect User Management',
 'CWE-287': 'Improper Authentication',
 'CWE-288': 'Authentication Bypass Using an Alternate Path or Channel',
 'CWE-289': 'Authentication Bypass by Alternate Name',
 'CWE-290': 'Authentication Bypass by Spoofing',
 'CWE-291': 'Reliance on IP Address for Authentication',
 'CWE-293': 'Using Referer Field for Authentication',
 'CWE-294': 'Authentication Bypass by Capture-replay',
 'CWE-295': 'Improper Certificate Validation',
 'CWE-296': "Improper Following of a Certificate's Chain of Trust",
 'CWE-297': 'Improper Validation of Certificate with Host Mismatch',
 'CWE-298': 'Improper Validation of Certificate Expiration',
 'CWE-299': 'Improper Check for Certificate Revocation',
 'CWE-300': 'Channel Accessible by Non-Endpoint',
 'CWE-301': 'Reflection Attack in an Authentication Protocol',
 'CWE-302': 'Authentication Bypass by Assumed-Immutable Data',
 'CWE-303': 'Incorrect Implementation of Authentication Algorithm',
 'CWE-304': 'Missing Critical Step in Authentication',
 'CWE-305': 'Authentication Bypass by Primary Weakness',
 'CWE-306': 'Missing Authentication for Critical Function',
 'CWE-307': 'Improper Restriction of Excessive Authentication Attempts',
 'CWE-308': 'Use of Single-factor Authentication',
 'CWE-309': 'Use of Password System for Primary Authentication',
 'CWE-311': 'Missing Encryption of Sensitive Data',
 'CWE-312': 'Cleartext Storage of Sensitive Information',
 'CWE-313': 'Cleartext Storage in a File or on Disk',
 'CWE-314': 'Cleartext Storage in the Registry',
 'CWE-315': 'Cleartext Storage of Sensitive Information in a Cookie',
 'CWE-316': 'Cleartext Storage of Sensitive Information in Memory',
 'CWE-317': 'Cleartext Storage of Sensitive Information in GUI',
 'CWE-318': 'Cleartext Storage of Sensitive Information in Executable',
 'CWE-319': 'Cleartext Transmission of Sensitive Information',
 'CWE-321': 'Use of Hard-coded Cryptographic Key',
 'CWE-322': 'Key Exchange without Entity Authentication',
 'CWE-323': 'Reusing a Nonce, Key Pair in Encryption',
 'CWE-324': 'Use of a Key Past its Expiration Date',
 'CWE-325': 'Missing Cryptographic Step',
 'CWE-326': 'Inadequate Encryption Strength',
 'CWE-327': 'Use of a Broken or Risky Cryptographic Algorithm',
 'CWE-328': 'Use of Weak Hash',
 'CWE-329': 'Generation of Predictable IV with CBC Mode',
 'CWE-330': 'Use of Insufficiently Random Values',
 'CWE-331': 'Insufficient Entropy',
 'CWE-332': 'Insufficient Entropy in PRNG',
 'CWE-333': 'Improper Handling of Insufficient Entropy in TRNG',
 'CWE-334': 'Small Space of Random Values',
 'CWE-335': 'Incorrect Usage of Seeds in Pseudo-Random Number Generator (PRNG)',
 'CWE-336': 'Same Seed in Pseudo-Random Number Generator (PRNG)',
 'CWE-337': 'Predictable Seed in Pseudo-Random Number Generator (PRNG)',
 'CWE-338': 'Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)',
 'CWE-339': 'Small Seed Space in PRNG',
 'CWE-340': 'Generation of Predictable Numbers or Identifiers',
 'CWE-341': 'Predictable from Observable State',
 'CWE-342': 'Predictable Exact Value from Previous Values',
 'CWE-343': 'Predictable Value Range from Previous Values',
 'CWE-344': 'Use of Invariant Value in Dynamically Changing Context',
 'CWE-345': 'Insufficient Verification of Data Authenticity',
 'CWE-346': 'Origin Validation Error',
 'CWE-347': 'Improper Verification of Cryptographic Signature',
 'CWE-348': 'Use of Less Trusted Source',
 'CWE-349': 'Acceptance of Extraneous Untrusted Data With Trusted Data',
 'CWE-350': 'Reliance on Reverse DNS Resolution for a Security-Critical Action',
 'CWE-351': 'Insufficient Type Distinction',
 'CWE-352': 'Cross-Site Request Forgery (CSRF)',
 'CWE-353': 'Missing Support for Integrity Check',
 'CWE-354': 'Improper Validation of Integrity Check Value',
 'CWE-356': 'Product UI does not Warn User of Unsafe Actions',
 'CWE-357': 'Insufficient UI Warning of Dangerous Operations',
 'CWE-358': 'Improperly Implemented Security Check for Standard',
 'CWE-359': 'Exposure of Private Personal Information to an Unauthorized Actor',
 'CWE-360': 'Trust of System Event Data',
 'CWE-362': "Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')",
 'CWE-363': 'Race Condition Enabling Link Following',
 'CWE-364': 'Signal Handler Race Condition',
 'CWE-366': 'Race Condition within a Thread',
 'CWE-367': 'Time-of-check Time-of-use (TOCTOU) Race Condition',
 'CWE-368': 'Context Switching Race Condition',
 'CWE-369': 'Divide By Zero',
 'CWE-370': 'Missing Check for Certificate Revocation after Initial Check',
 'CWE-372': 'Incomplete Internal State Distinction',
 'CWE-374': 'Passing Mutable Objects to an Untrusted Method',
 'CWE-375': 'Returning a Mutable Object to an Untrusted Caller',
 'CWE-377': 'Insecure Temporary File',
 'CWE-378': 'Creation of Temporary File With Insecure Permissions',
 'CWE-379': 'Creation of Temporary File in Directory with Insecure Permissions',
 'CWE-382': 'J2EE Bad Practices: Use of System.exit()',
 'CWE-383': 'J2EE Bad Practices: Direct Use of Threads',
 'CWE-384': 'Session Fixation',
 'CWE-385': 'Covert Timing Channel',
 'CWE-386': 'Symbolic Name not Mapping to Correct Object',
 'CWE-390': 'Detection of Error Condition Without Action',
 'CWE-391': 'Unchecked Error Condition',
 'CWE-392': 'Missing Report of Error Condition',
 'CWE-393': 'Return of Wrong Status Code',
 'CWE-394': 'Unexpected Status Code or Return Value',

In [ ]:
df_pypi_sorted_by_count.head(15)["PyPI_Count"]

CWE-79     441.0
CWE-22     348.0
CWE-20     280.0
CWE-200    210.0
CWE-400    198.0
CWE-94     190.0
CWE-502    188.0
CWE-918    147.0
CWE-770    130.0
CWE-787    109.0
CWE-125    109.0
CWE-863    102.0
CWE-601    100.0
CWE-78      99.0
CWE-89      99.0
Name: PyPI_Count, dtype: float64

In [ ]:
most_py_cwes = df_pypi_sorted_by_count.head(15)["PyPI_Count"].index

In [ ]:
most_npm_cwes = df_npm_sorted_by_count.head(15)["npm_Count"].index

In [ ]:
most_go_cwes = df_go_sorted_by_count.head(15)["Go_Count"].index

In [ ]:
if __name__ == "__main__":
    for name in ECOSYSTEMS.keys():
        metric_col = f"{name}_Metric"

        # Проверяем, что колонка существует (на случай, если экосистема была пустой)
        if metric_col in df_final.columns:
            # Получаем 10 самых больших значений из колонки метрики
            top_10 = df_final[metric_col].nlargest(20)

            print(f"\n🚀 Экосистема: {name}")
            print("-" * 35)

            # Выводим с нумерацией
            for rank, (cwe, score) in enumerate(top_10.items(), start=1):
                # Если метрика равна 0, значит значимых уязвимостей больше нет
                if score == 0:
                    break

                # Достаем количество (Count) для полноты картины
                count_col = f"{name}_Count"
                cwe_count = int(df_final.at[cwe, count_col])

                # Форматированный вывод (выравнивание пробелами для красоты)
                print(f"{rank:2d}. {cwe:<10} | Метрика: {score:10,.2f} | С какой областью связана уязвимость: {cwe_dict[cwe]} | Кол-во: {cwe_count}")

    print("\n" + "="*50)

🚀 Экосистема: PyPI
-----------------------------------
 1. CWE-242    | Метрика:  20,354.60 | С какой областью связана уязвимость: Use of Inherently Dangerous Function | Кол-во: 1
 2. CWE-197    | Метрика:  17,955.00 | С какой областью связана уязвимость: Numeric Truncation Error | Кол-во: 1
 3. CWE-336    | Метрика:  17,025.00 | С какой областью связана уязвимость: Same Seed in Pseudo-Random Number Generator (PRNG) | Кол-во: 1
 4. CWE-1056   | Метрика:  16,032.80 | С какой областью связана уязвимость: Invokable Control Element with Variadic Parameters | Кол-во: 1
 5. CWE-641    | Метрика:  14,106.40 | С какой областью связана уязвимость: Improper Restriction of Names for Files and Other Resources | Кол-во: 1
 6. CWE-391    | Метрика:  13,567.50 | С какой областью связана уязвимость: Unchecked Error Condition | Кол-во: 1
 7. CWE-527    | Метрика:  12,253.60 | С какой областью связана уязвимость: Exposure of Version-Control Repository to an Unauthorized Control Sphere | Кол-во: 1
 8. CWE-279    | Метрика:  12,086.80 | С какой областью связана уязвимость: Incorrect Execution-Assigned Permissions | Кол-во: 1
 9. CWE-788    | Метрика:  11,959.20 | С какой областью связана уязвимость: Access of Memory Location After End of Buffer | Кол-во: 1
10. CWE-824    | Метрика:  11,601.77 | С какой областью связана уязвимость: Access of Uninitialized Pointer | Кол-во: 16
11. CWE-304    | Метрика:  10,308.45 | С какой областью связана уязвимость: Missing Critical Step in Authentication | Кол-во: 2
12. CWE-590    | Метрика:  10,300.50 | С какой областью связана уязвимость: Free of Memory not on the Heap | Кол-во: 1
13. CWE-12     | Метрика:   9,647.95 | С какой областью связана уязвимость: ASP.NET Misconfiguration: Missing Custom Error Page | Кол-во: 2
14. CWE-134    | Метрика:   9,610.00 | С какой областью связана уязвимость: Use of Externally-Controlled Format String | Кол-во: 6
15. CWE-64     | Метрика:   9,479.40 | С какой областью связана уязвимость: Windows Shortcut Following (.LNK) | Кол-во: 1
16. CWE-923    | Метрика:   9,270.95 | С какой областью связана уязвимость: Improper Restriction of Communication Channel to Intended Endpoints | Кол-во: 2
17. CWE-358    | Метрика:   9,165.60 | С какой областью связана уязвимость: Improperly Implemented Security Check for Standard | Кол-во: 4
18. CWE-96     | Метрика:   8,972.60 | С какой областью связана уязвимость: Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection') | Кол-во: 1
19. CWE-640    | Метрика:   8,742.17 | С какой областью связана уязвимость: Weak Password Recovery Mechanism for Forgotten Password | Кол-во: 3
20. CWE-1321   | Метрика:   8,710.34 | С какой областью связана уязвимость: Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution') | Кол-во: 5

🚀 Экосистема: npm
-----------------------------------
 1. CWE-253    | Метрика:  21,393.40 | С какой областью связана уязвимость: Incorrect Check of Function Return Value | Кол-во: 1
 2. CWE-425    | Метрика:  21,143.45 | С какой областью связана уязвимость: Direct Request ('Forced Browsing') | Кол-во: 2
 3. CWE-303    | Метрика:  15,188.80 | С какой областью связана уязвимость: Incorrect Implementation of Authentication Algorithm | Кол-во: 1
 4. CWE-1255   | Метрика:  14,842.50 | С какой областью связана уязвимость: Comparison Logic is Vulnerable to Power Side-Channel Attacks | Кол-во: 1
 5. CWE-471    | Метрика:  14,320.55 | С какой областью связана уязвимость: Modification of Assumed-Immutable Data (MAID) | Кол-во: 13
 6. CWE-311    | Метрика:  13,822.69 | С какой областью связана уязвимость: Missing Encryption of Sensitive Data | Кол-во: 53
 7. CWE-527    | Метрика:  12,253.60 | С какой областью связана уязвимость: Exposure of Version-Control Repository to an Unauthorized Control Sphere | Кол-во: 1
 8. CWE-547    | Метрика:  11,785.20 | С какой областью связана уязвимость: Use of Hard-coded, Security-relevant Constants | Кол-во: 1
 9. CWE-338    | Метрика:  11,733.10 | С какой областью связана уязвимость: Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG) | Кол-во: 5
10. CWE-565    | Метрика:  11,446.50 | С какой областью связана уязвимость: Reliance on Cookies without Validation and Integrity Checking | Кол-во: 1
11. CWE-509    | Метрика:  11,387.60 | С какой областью связана уязвимость: Replicating Malicious Code (Virus or Worm) | Кол-во: 1
12. CWE-1254   | Метрика:  11,296.90 | С какой областью связана уязвимость: Incorrect Comparison Logic Granularity | Кол-во: 2
13. CWE-433    | Метрика:  10,546.62 | С какой областью связана уязвимость: Unparsed Raw Web Content Delivery | Кол-во: 4
14. CWE-544    | Метрика:  10,538.10 | С какой областью связана уязвимость: Missing Standardized Error Handling Mechanism | Кол-во: 1
15. CWE-29     | Метрика:  10,135.83 | С какой областью связана уязвимость: Path Traversal: '..filename' | Кол-во: 3
16. CWE-27     | Метрика:   9,817.50 | С какой областью связана уязвимость: Path Traversal: 'dir/../../filename' | Кол-во: 1
17. CWE-64     | Метрика:   9,294.37 | С какой областью связана уязвимость: Windows Shortcut Following (.LNK) | Кол-во: 3
18. CWE-912    | Метрика:   8,875.17 | С какой областью связана уязвимость: Hidden Functionality | Кол-во: 3
19. CWE-335    | Метрика:   8,569.65 | С какой областью связана уязвимость: Incorrect Usage of Seeds in Pseudo-Random Number Generator (PRNG) | Кол-во: 2
20. CWE-915    | Метрика:   7,699.01 | С какой областью связана уязвимость: Improperly Controlled Modification of Dynamically-Determined Object Attributes | Кол-во: 85

🚀 Экосистема: Go
-----------------------------------
 1. CWE-304    | Метрика:  16,513.00 | С какой областью связана уязвимость: Missing Critical Step in Authentication | Кол-во: 1
 2. CWE-1236   | Метрика:  13,230.00 | С какой областью связана уязвимость: Improper Neutralization of Formula Elements in a CSV File | Кол-во: 1
 3. CWE-372    | Метрика:  11,128.00 | С какой областью связана уязвимость: Incomplete Internal State Distinction | Кол-во: 1
 4. CWE-776    | Метрика:  10,642.50 | С какой областью связана уязвимость: Improper Restriction of Recursive Entity References in DTDs ('XML Entity Expansion') | Кол-во: 2
 5. CWE-267    | Метрика:  10,008.90 | С какой областью связана уязвимость: Privilege Defined With Unsafe Actions | Кол-во: 1
 6. CWE-1050   | Метрика:   9,789.00 | С какой областью связана уязвимость: Excessive Platform Resource Consumption within a Loop | Кол-во: 1
 7. CWE-921    | Метрика:   9,015.50 | С какой областью связана уязвимость: Storage of Sensitive Data in a Mechanism without Access Control | Кол-во: 1
 8. CWE-332    | Метрика:   8,908.50 | С какой областью связана уязвимость: Insufficient Entropy in PRNG | Кол-во: 2
 9. CWE-1270   | Метрика:   8,836.00 | С какой областью связана уязвимость: Generation of Incorrect Security Tokens | Кол-во: 1
10. CWE-300    | Метрика:   8,106.00 | С какой областью связана уязвимость: Channel Accessible by Non-Endpoint | Кол-во: 1
11. CWE-228    | Метрика:   7,713.50 | С какой областью связана уязвимость: Improper Handling of Syntactically Invalid Structure | Кол-во: 2
12. CWE-1100   | Метрика:   7,494.50 | С какой областью связана уязвимость: Insufficient Isolation of System-Dependent Functions | Кол-во: 1
13. CWE-475    | Метрика:   7,492.50 | С какой областью связана уязвимость: Undefined Behavior for Input to API | Кол-во: 1
14. CWE-29     | Метрика:   7,348.00 | С какой областью связана уязвимость: Path Traversal: '..filename' | Кол-во: 1
15. CWE-283    | Метрика:   7,280.00 | С какой областью связана уязвимость: Unverified Ownership | Кол-во: 1
16. CWE-113    | Метрика:   7,194.20 | С какой областью связана уязвимость: Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Request/Response Splitting') | Кол-во: 2
17. CWE-119    | Метрика:   6,954.52 | С какой областью связана уязвимость: Improper Restriction of Operations within the Bounds of a Memory Buffer | Кол-во: 8
18. CWE-115    | Метрика:   6,665.16 | С какой областью связана уязвимость: Misinterpretation of Input | Кол-во: 5
19. CWE-340    | Метрика:   6,626.10 | С какой областью связана уязвимость: Generation of Predictable Numbers or Identifiers | Кол-во: 2
20. CWE-834    | Метрика:   6,514.42 | С какой областью связана уязвимость: Excessive Iteration | Кол-во: 5

==================================================

In [72]:
def find_longest_upstream_chains(graph, eco_map):
    print("\n--- Анализ графа Upstream ---")
    memo = {}        # Кэш длин: { "ID": длина }
    path_memo = {}   # Кэш самих путей: { "ID": ["ID1", "ID2", ...] }

    def dfs(node):
        # Если уже считали этот узел, просто возвращаем результат
        if node in memo:
            return memo[node], path_memo[node]

        # Если у узла нет upstream (или его нет в нашем графе), длина 1
        if node not in graph or not graph[node]:
            return 1, [node]

        max_len = 0
        best_path = []

        # Проверяем все ветки upstream и ищем самую длинную
        for neighbor in graph[node]:
            length, path = dfs(neighbor)
            if length > max_len:
                max_len = length
                best_path = path

        # Сохраняем результат: свой узел + лучший путь из соседей
        memo[node] = max_len + 1
        path_memo[node] = [node] + best_path

        return memo[node], path_memo[node]

    # 1. Считаем длины для всех узлов
    for node in graph.keys():
        dfs(node)

    # 2. Группируем рекорды по экосистемам
    longest_by_eco = {eco: {"length": 0, "path": []} for eco in set(eco_map.values())}

    for node, length in memo.items():
        eco = eco_map.get(node)
        if not eco:
            continue # Если узел "внешний", пропускаем

        if length > longest_by_eco[eco]["length"]:
            longest_by_eco[eco]["length"] = length
            longest_by_eco[eco]["path"] = path_memo[node]

    # 3. Выводим результаты
    for eco, data in longest_by_eco.items():
        print(f"\n🌐 Экосистема: {eco}")
        if data['length'] > 1:
            print(f"Самая длинная цепочка: {data['length']} узлов")
            print(" -> ".join(data['path']))
        else:
            print("В этой экосистеме нет иерархии upstream (все цепочки длиной 1).")

    return longest_by_eco

In [74]:
ans = find_longest_upstream_chains(upstream_graph, ecosystem_map)

--- Анализ графа Upstream ---

🌐 Экосистема: npm
В этой экосистеме нет иерархии upstream (все цепочки длиной 1).

🌐 Экосистема: PyPI
В этой экосистеме нет иерархии upstream (все цепочки длиной 1).

🌐 Экосистема: Go
В этой экосистеме нет иерархии upstream (все цепочки длиной 1).